import React from 'react';

const TermsOfService = () => {
    return (
        <div className="terms-of-service">
            <h1>Terms of Service</h1>
            <p>Welcome to PlatePal!</p>
            <p>
                These terms and conditions outline the rules and regulations for the use of PlatePal's App.
                By accessing this app we assume you accept these terms and conditions in full. Do not continue to use
                PlatePal's app if you do not accept all of the terms and conditions stated on this page.
            </p>

            <h2>License</h2>
            <p>
                Unless otherwise stated, PlatePal and/or its licensors own the intellectual property rights for all
                material on PlatePal. All intellectual property rights are reserved. You may view and/or print pages
                from PlatePal for your own personal use subject to restrictions set in these terms and conditions.
            </p>
            <p>You must not:</p>
            <ul>
                <li>Republish material from PlatePal</li>
                <li>Sell, rent, or sub-license material from PlatePal</li>
                <li>Reproduce, duplicate, or copy material from PlatePal</li>
                <li>Redistribute content from PlatePal (unless content is specifically made for redistribution)</li>
            </ul>

            <h2>User Accounts</h2>
            <p>
                When you create an account with us, you must provide us information that is accurate, complete, and
                current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate
                termination of your account on our Service.
            </p>
            <p>
                You are responsible for safeguarding the password that you use to access the Service and for any
                activities or actions under your password, whether your password is with our Service or a third-party
                service.
            </p>
            <p>
                You agree not to disclose your password to any third party. You must notify us immediately upon becoming
                aware of any breach of security or unauthorized use of your account.
            </p>

            <h2>Generated Recipes</h2>
            <p>
                PlatePal generates recipes based on the ingredients you input. While we strive to provide accurate and
                useful recipes, we do not guarantee the accuracy, reliability, or completeness of any recipes generated
                by the app.
            </p>
            <p>
                PlatePal is not responsible for any adverse effects or damages resulting from the use or preparation of
                recipes generated by the app. Use recipes at your own risk.
            </p>

            <h2>Content Upload</h2>
            <p>
                By uploading content to PlatePal, you grant PlatePal a non-exclusive, royalty-free, transferable,
                sub-licensable, worldwide license to use, store, display, reproduce, modify, create derivative works,
                perform, and distribute your content on PlatePal solely for the purposes of operating, developing,
                providing, and using the PlatePal app.
            </p>

            <h2>Termination</h2>
            <p>
                We may terminate or suspend access to our Service immediately, without prior notice or liability, for
                any reason whatsoever, including without limitation if you breach the Terms.
            </p>
            <p>
                All provisions of the Terms which by their nature should survive termination shall survive termination,
                including, without limitation, ownership provisions, warranty disclaimers, indemnity, and limitations of
                liability.
            </p>

            <h2>Changes</h2>
            <p>
                We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a
                revision is material we will try to provide at least 30 days' notice prior to any new terms taking
                effect. What constitutes a material change will be determined at our sole discretion.
            </p>

            <p>If you have any questions about these Terms, please contact us at platepalservice@gmail.com.</p>
        </div>
    );
};

export default TermsOfService;
